pdf_dir: path/to/pdfs
run_id: example_run
llm_model: gpt-4
embedding_model: text-embedding-3-large
num_runs: 1
questions:
  - slug: patient_outcomes
    text: "How can AI technologies be utilised to enhance patient outcomes in nursing?"
output_dir: output
rounds:
  question: "Summarize the paper"
  chunk_size: 2000
  round1:
    top_n: 1
    temperature: 0.7
  round2:
    temperature: 0
