[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "paperqa2"
version = "0.1.0"
description = "Paper QA extraction pipeline"
readme = "README.md"
requires-python = ">=3.10"

[project.scripts]
paperqa2 = "paperqa2.cli:main"
